### ISSUE TITLE
Windows Authentication

### ISSUE THREAD

**Issue by ghost** [emacs-lsp/lsp-mssql#12]
I don't seem to be able to connect using Windows Authentication instead of username/password (which is disabled for our server). It seems like it should be possible since it works with vscode. Any help?

**Comment by yyoncho** [comment]
Have you tried the same connection string as the one suggested for vscode?

**Comment by ghost** [comment]
`Data Source=myserver;Initial Catalog=mydb; Integrated Security=true` works in vscode. I'm not sure how to translate that to the connection example for lsp-mssql

```lisp
(setq lsp-mssql-connections
      [(:server "myserver"
                :database "mydb"
                ;; :integrated-security "true" ???
                :user ""
                :password "")])
```


Everything I've tried returns  `LSP :: Failed to connect with the following error error number: 0
nil`

**Comment by ghost** [comment]
For more reference, here is an example connection setting from Azure Data Studio settings:

```json
  "datasource.connections": [
        {
            "options": {
                "connectionName": "My Server",
                "server": "myserver",
                "database": "mydb",
                "authenticationType": "Integrated",
                "user": "",
                "password": "",
                "applicationName": "azdata",
                "originalDatabase": "mydb",
                "groupId": "86b7c670-2ba4-49ce-8115-20ba8b5983bf",
                "databaseDisplayName": "My DB"
            },
            "groupId": "86b7c670-2ba4-49ce-8115-20ba8b5983bf",
            "providerName": "MSSQL",
            "savePassword": true,
            "id": "75cee440-d0f1-4c86-9932-01e4e1a48093"
        },
```

If I try something like 
```lisp
(setq lsp-mssql-connections
[(:server "myserver"
:database "mydb"
:authenticationType "Integrated"
:user ""
:password ""
)])
```

I get 

``` 
LSP :: Failed to connect with the following error error number: 53
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
```

I do not see a failed login attempt on the server using `exec sp_readerrorlog 0, 1, 'Login failed'`

**Comment by yyoncho** [comment]
@fingolfin19 don't put user and password and use `localhost` for server. 

I used this: https://learn.microsoft.com/en-us/sql/tools/visual-studio-code/sql-server-develop-use-vscode?view=sql-server-ver16 as a guide.

**Comment by ghost** [comment]
> @fingolfin19 don't put user and password 
 
Same result as the example above with empty strings.

> and use `localhost` for server.
 
I'm not connecting to a local database. I'm connecting to a host on our vpn network.

I will poke around more later if I find the time, but I am not very familiar with elisp or c# to follow what the programs are trying to do.  
 
Conceptually adding a `:option value` to the connection variable should be exactly the same thing as setting an option in json in vscode/Azure Data Studio, right? Is there something I can be doing to get more logging or error outputs?
 
I tried running the MicrosoftSqlToolsServiceLayer.exe directly in command lines but MS's docs don't seem to me to be very helpful.

**Comment by yyoncho** [comment]
> Conceptually adding a `:option value` to the connection variable should be exactly the same thing as setting an option in json in vscode/Azure Data Studio, right?

The same as in vscode, I am not familiar with azure data studio so you can look for vscode related resources when searching for solution. Note that both vscode and emacs are sending the connection string to the language server and it connects to the remote db.

**Comment by ghost** [comment]
Tried one last thing and for some reason this way the connection works:

```lisp
(setq lsp-mssql-connections
[(:connectionString "Data Source=myserver;Initial Catalog=mydb; Integrated Security=true"
                    :server "myserver"
)])
```
No idea why the result for that would be any different.
