### ISSUE TITLE
Issues with connecting to server

### ISSUE THREAD

**Issue by ivanruski** [emacs-lsp/lsp-mssql#8]
Hi,
I am trying to set-up `lsp-mssql`. I have followed the instructions from [here](https://emacs-lsp.github.io/lsp-mssql/).
However I get the following error when I try to do `lsp-mssql-connect`:
> lsp--send-request-async: The connected server(s) does not support method connection/connect.
> To find out what capabilities support your server use ‘M-x lsp-describe-session’
> and expand the capabilities section

I have placed the **MicrosoftSqlToolsServiceLayer** in the `.emacs.d/mssql` folder (emacs downloads a .rar in my User/Temp folder which I've extracted in mssql folder) also after I got the [sqls](https://github.com/lighttiger2505/sqls) I have set the `lsp-sqls-server` to point to the sqls executable.
My  *lsp-log* buffer has the following contents:
> Command "/emacs.d/mssql/MicrosoftSqlToolsServiceLayer" is present on the path.
> Command "/.emacs.d/mssql/sqls" is present on the path.
> Found the following clients for /lsp/play.sql: (server-id sql, priority -1), (server-id sqls, priority -1)
> The following clients were selected based on priority: (server-id sql, priority -1)

Also I am using SQLEPXRESS and when I run `lsp-describe-session` I get 
> -  /lsp

What am I doing correct and what am I doing wrong ? 
Some help would be greatly appreciated. 
Thanks

**Comment by yyoncho** [comment]
My guess is that the server has crashed. Check stderr buffer.

**Comment by ivanruski** [comment]
> My guess is that the server has crashed. Check stderr buffer.

stderr buffer of what ?
Which server .. the sql language server ?

**Comment by yyoncho** [comment]
For each language server there is a buffer named like *<server-id>: stdderr*. Do you see it? If now, what happens when you do M-x lsp in sql file? If it does not yield an error message, what do you have in M-x lsp-describe-session buffer?

**Comment by ivanruski** [comment]
I don't see the : stdderr buffer.

When I do M-x lsp-describe-session I get the following

> - c:/Users/IvanIvanov/lsp
> - c:/Users/IvanIvanov/Desktop/lsp

When I do M-x lsp in sql file I get the following in my messages buffer

> lsp--start-connection: Wrong type argument: listp, #s(lsp--client nil
> nil (:connect #[1028 "ÂÀ!Ã!Ä!ÅÆ\"ÇÈÉÊËÅÌ
> \"ÍÎÏÐÑÒÓÔ&ÕÖ\"Õ×!Ö\"rØ!qÙ
> )B¶)" [#[0 "ÁÂ\"Ã!\0C
> \0ÄÅ!\0Æ C \0ÇÈ!" [lsp-mssql-download-location
> f-join "MicrosoftSqlToolsServiceLayer" executable-find y-or-n-p "The
> mssql server is not present. Do you want to download it? "
> lsp-mssql-download-server user-error "Server is not installed? "] 3]
> process-environment lsp-resolve-final-function
> generate-new-buffer-name lsp--compute-process-environment format
> "*%s::stderr*" make-process :name :connection-type ...] 26 "
> 
> (fn FILTER SENTINEL NAME ENVIRONMENT-FN)"] :test\? #[0 "ÁÂÀ!!"
> [#[0 "ÁÂ\"Ã!\0C \0ÄÅ!\0Æ C
> \0ÇÈ!" [lsp-mssql-download-location f-join
> "MicrosoftSqlToolsServiceLayer" executable-find y-or-n-p "The mssql
> server is not present. Do you want to download it? "
> lsp-mssql-download-server user-error "Server is not installed? "] 3]
> lsp-server-present\? lsp-resolve-final-function] 3]) nil nil
> #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold
> 0.8125 data ("objectexplorer/expandCompleted"
> lsp-mssql--expand-completed "objectexplorer/sessioncreated"
> lsp-mssql--session-created "connection/complete"
> lsp-mssql--connection-complete "connection/connectionchanged"
> lsp-mssql--connection-changed "telemetry/sqlevent" ignore
> "textDocument/intelliSenseReady" ignore "query/resultSetAvailable"
> lsp-mssql--result-set-available "query/message" lsp-mssql--message
> "query/resultSetUpdated" lsp-mssql--result-set-updated
> "query/resultSetComplete" lsp-mssql--result-set-complete ...))
> #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold
> 0.8125 data ( ...)) #s(hash-table size 65 test eql rehash-size 1.5
> rehash-threshold 0.8125 data ( ...)) nil ...)
